=== hoverjet/mymusic-rails-api/spec/support/api/schemas/artists.json
{
   "$schema":"http://json-schema.org/draft-04/hyper-schema",
   "id":"/schemata/artists",
   "title":"Artists",
   "description":"Artist Collection Schema",
   "stability":"prototype",
   "strictProperties":true,
   "required":[
      "links"
   ],
   "type":[
      "object"
   ],
   "definitions":{
      "id":{
         "description":"unique id of artist",
         "readOnly":true,
         "type":[
            "integer"
         ]
      },
      "artist_properties":{
         "$ref":"file:spec/support/api/schemas/partials/artist_properties.json#"
      },
      "genre_properties":{
         "$ref":"file:spec/support/api/schemas/partials/genre_properties.json#"
      },
      "identity":{
         "anyOf":[
            {
               "$ref":"/schemata/artist#/definitions/id"
            }
         ]
      },
      "links":{
         "type":"array",
         "items":[
            {
               "properties":{
                  "rel":{
                     "type":"array",
                     "items":[
                        {
                           "type":"string",
                           "enum":[
                              "self"
                           ]
                        }
                     ]
                  },
                  "href":{
                     "type":"string",
                     "format":"uri"
                  }
               }
            },
            {
               "properties":{
                  "rel":{
                     "type":"array",
                     "items":[
                        {
                           "type":"string",
                           "enum":[
                              "collection"
                           ]
                        }
                     ]
                  },
                  "href":{
                     "type":"string",
                     "format":"uri"
                  }
               }
            }
         ]
      }
   },
   "properties":{
      "class":{
         "type":"array",
         "items":{
            "type":"string",
            "enum":[
               "artists"
            ]
         }
      },
      "rel":{
         "type":"array",
         "items":{
            "type":"string",
            "enum":[
               "collection"
            ]
         }
      },

      "total_count":{
         "type" : "integer"

         },
      "total_pages":{
         "type" : "integer"

         },
      "page_size":{
         "type" : "integer"

         },


      "properties":{
         "$ref":"/schemata/artist#/definitions/artist_properties"
      },
      "actions":{
         "type":"array",
         "items":[
            {
               "type":"object",
               "properties":{
                  "name":{
                     "type":"string",
                     "enum":[
                        "update-artist"
                     ]
                  },
                  "title":{
                     "type":"string",
                     "enum":[
                        "Update Artist"
                     ]
                  },
                  "method":{
                     "type":"string",
                     "enum":[
                        "PATCH"
                     ]
                  },
                  "type":{
                     "type":"string",
                     "enum":[
                        "application/x-www-form-urlencoded"
                     ]
                  },
                  "href":{
                     "type":"string",
                     "format":"uri"
                  },
                  "fields":{
                     "type":"array",
                     "items":[
                        {
                           "properties":{
                              "name":{
                                 "type":"string",
                                 "enum":[
                                    "artist[title]"
                                 ]
                              },
                              "type":{
                                 "type":"string",
                                 "enum":[
                                    "text"
                                 ]
                              }
                           }
                        },
                        {
                           "properties":{
                              "name":{
                                 "type":"string",
                                 "enum":[
                                    "artist[country]"
                                 ]
                              },
                              "type":{
                                 "type":"string",
                                 "enum":[
                                    "text"
                                 ]
                              }
                           }
                        },
                        {
                           "properties":{
                              "name":{
                                 "type":"string",
                                 "enum":[
                                    "artist[genre_id]"
                                 ]
                              },
                              "type":{
                                 "type":"string",
                                 "enum":[
                                    "number"
                                 ]
                              }
                           }
                        }
                     ]
                  }
               }
            },
            {
               "type":"object",
               "properties":{
                  "name":{
                     "type":"string",
                     "enum":[
                        "delete-artist"
                     ]
                  },
                  "title":{
                     "type":"string",
                     "enum":[
                        "Delete Artist"
                     ]
                  },
                  "method":{
                     "type":"string",
                     "enum":[
                        "DELETE"
                     ]
                  },
                  "type":{
                     "type":"string",
                     "enum":[
                        "application/x-www-form-urlencoded"
                     ]
                  },
                  "href":{
                     "type":"string",
                     "format":"uri"
                  }
               }
            }
         ]
      },
      "entities":{
         "type":"array",
         "minItems":0,
         "items":[
            {
               "anyOf":[
                  {
                     "type":"object",
                     "properties":{
                        "class":{
                           "type":"array",
                           "items":{
                              "type":"string",
                              "enum":[
                                 "genre"
                              ]
                           }
                        },
                        "rel":{
                           "type":"array",
                           "items":{
                              "type":"string",
                              "enum":[
                                 "related"
                              ]
                           }
                        },
                        "properties":{
                           "id":{
                              "type":"integer"
                           },
                           "title":{
                              "type":"string"
                           },
                           "created_at":{
                              "type":"string",
                              "format":"date-time"
                           },
                           "updated_at":{
                              "type":"string",
                              "format":"date-time"
                           }
                        },
                        "links":{
                           "type":"array",
                           "items":[
                              {
                                 "rel":{
                                    "type":"array",
                                    "items":{
                                       "type":"string",
                                       "enum":[
                                          "collection"
                                       ]
                                    }
                                 },
                                 "href":{
                                    "type":"string",
                                    "format":"uri"
                                 }
                              }
                           ]
                        }
                     }
                  },
                  {
                     "type":"object",
                     "properties":{
                        "class":{
                           "type":"array",
                           "items":{
                              "type":"string",
                              "enum":[
                                 "albums"
                              ]
                           }
                        },
                        "href":{
                           "type":"string",
                           "format":"uri"
                        },
                        "rel":{
                           "type":"array",
                           "items":{
                              "type":"string",
                              "enum":[
                                 "related"
                              ]
                           }
                        }
                     }
                  }
               ]
            }
         ]
      },
      "links":{
         "$ref":"/schemata/artist#/definitions/links"
      }
   }
}

=== hoverjet/mymusic-rails-api/art_bluepri.json
{
  "class": [
    "artists"
  ],
  "rel": [
    "collection"
  ],
  "total_count": 10,
  "total_pages": 1,
  "page_size": 10,
  "entities": [
    {
      "class": [
        "artist"
      ],
      "rel": [
        "item"
      ],
      "properties": {
        "id": 1,
        "title": "King Diamond",
        "country": "Denmark",
        "genre_id": 2,
        "created_at": "2016-01-30T10:19:27.000Z",
        "updated_at": "2016-01-30T10:19:27.000Z"
      },
      "links": [
        {
          "rel": [
            "self"
          ],
          "href": "http://api.app.me:3000/v1/artists/1"
        }
      ],
      "entities": [
        [
          {
            "class": [
              "albums"
            ],
            "href": "http://api.app.me:3000/v1/albums/id/1,2,3,4/page/1/per/10",
            "rel": [
              "related"
            ]
          },
          {
            "class": [
              "genre"
            ],
            "rel": [
              "related"
            ],
            "properties": {
              "id": 2,
              "title": "Metal",
              "created_at": "2016-01-30T10:19:26.000Z",
              "updated_at": "2016-01-30T10:19:26.000Z"
            },
            "links": [
              {
                "rel": [
                  "collection"
                ],
                "href": "http://api.app.me:3000/v1/genres"
              }
            ]
          }
        ]
      ]
    },
    {
      "class": [
        "artist"
      ],
      "rel": [
        "item"
      ],
      "properties": {
        "id": 2,
        "title": "Annihilator",
        "country": "Canada",
        "genre_id": 2,
        "created_at": "2016-01-30T10:19:27.000Z",
        "updated_at": "2016-01-30T10:19:27.000Z"
      },
      "links": [
        {
          "rel": [
            "self"
          ],
          "href": "http://api.app.me:3000/v1/artists/2"
        }
      ],
      "entities": [
        [
          {
            "class": [
              "genre"
            ],
            "rel": [
              "related"
            ],
            "properties": {
              "id": 2,
              "title": "Metal",
              "created_at": "2016-01-30T10:19:26.000Z",
              "updated_at": "2016-01-30T10:19:26.000Z"
            },
            "links": [
              {
                "rel": [
                  "collection"
                ],
                "href": "http://api.app.me:3000/v1/genres"
              }
            ]
          }
        ]
      ]
    },
    {
      "class": [
        "artist"
      ],
      "rel": [
        "item"
      ],
      "properties": {
        "id": 3,
        "title": "Kip Winger",
        "country": "USA",
        "genre_id": 1,
        "created_at": "2016-01-30T10:19:27.000Z",
        "updated_at": "2016-01-30T10:19:27.000Z"
      },
      "links": [
        {
          "rel": [
            "self"
          ],
          "href": "http://api.app.me:3000/v1/artists/3"
        }
      ],
      "entities": [
        [
          {
            "class": [
              "genre"
            ],
            "rel": [
              "related"
            ],
            "properties": {
              "id": 1,
              "title": "Rock",
              "created_at": "2016-01-30T10:19:26.000Z",
              "updated_at": "2016-01-30T10:19:26.000Z"
            },
            "links": [
              {
                "rel": [
                  "collection"
                ],
                "href": "http://api.app.me:3000/v1/genres"
              }
            ]
          }
        ]
      ]
    },
    {
      "class": [
        "artist"
      ],
      "rel": [
        "item"
      ],
      "properties": {
        "id": 4,
        "title": "Katy Perry",
        "country": "USA",
        "genre_id": 3,
        "created_at": "2016-01-30T10:19:27.000Z",
        "updated_at": "2016-01-30T10:19:27.000Z"
      },
      "links": [
        {
          "rel": [
            "self"
          ],
          "href": "http://api.app.me:3000/v1/artists/4"
        }
      ],
      "entities": [
        [
          {
            "class": [
              "albums"
            ],
            "href": "http://api.app.me:3000/v1/albums/id/5,6,7/page/1/per/10",
            "rel": [
              "related"
            ]
          },
          {
            "class": [
              "genre"
            ],
            "rel": [
              "related"
            ],
            "properties": {
              "id": 3,
              "title": "Pop",
              "created_at": "2016-01-30T10:19:26.000Z",
              "updated_at": "2016-01-30T10:19:26.000Z"
            },
            "links": [
              {
                "rel": [
                  "collection"
                ],
                "href": "http://api.app.me:3000/v1/genres"
              }
            ]
          }
        ]
      ]
    },
    {
      "class": [
        "artist"
      ],
      "rel": [
        "item"
      ],
      "properties": {
        "id": 5,
        "title": "Fleur East",
        "country": "UK",
        "genre_id": 3,
        "created_at": "2016-01-30T10:19:27.000Z",
        "updated_at": "2016-01-30T10:19:27.000Z"
      },
      "links": [
        {
          "rel": [
            "self"
          ],
          "href": "http://api.app.me:3000/v1/artists/5"
        }
      ],
      "entities": [
        [
          {
            "class": [
              "albums"
            ],
            "href": "http://api.app.me:3000/v1/albums/id/12/page/1/per/10",
            "rel": [
              "related"
            ]
          },
          {
            "class": [
              "genre"
            ],
            "rel": [
              "related"
            ],
            "properties": {
              "id": 3,
              "title": "Pop",
              "created_at": "2016-01-30T10:19:26.000Z",
              "updated_at": "2016-01-30T10:19:26.000Z"
            },
            "links": [
              {
                "rel": [
                  "collection"
                ],
                "href": "http://api.app.me:3000/v1/genres"
              }
            ]
          }
        ]
      ]
    },
    {
      "class": [
        "artist"
      ],
      "rel": [
        "item"
      ],
      "properties": {
        "id": 6,
        "title": "Snarky Puppy",
        "country": "USA",
        "genre_id": 6,
        "created_at": "2016-01-30T10:19:27.000Z",
        "updated_at": "2016-01-30T10:19:27.000Z"
      },
      "links": [
        {
          "rel": [
            "self"
          ],
          "href": "http://api.app.me:3000/v1/artists/6"
        }
      ],
      "entities": [
        [
          {
            "class": [
              "genre"
            ],
            "rel": [
              "related"
            ],
            "properties": {
              "id": 6,
              "title": "Fusion",
              "created_at": "2016-01-30T10:19:26.000Z",
              "updated_at": "2016-01-30T10:19:26.000Z"
            },
            "links": [
              {
                "rel": [
                  "collection"
                ],
                "href": "http://api.app.me:3000/v1/genres"
              }
            ]
          }
        ]
      ]
    },
    {
      "class": [
        "artist"
      ],
      "rel": [
        "item"
      ],
      "properties": {
        "id": 7,
        "title": "Brian Tyler",
        "country": "USA",
        "genre_id": 7,
        "created_at": "2016-01-30T10:19:27.000Z",
        "updated_at": "2016-01-30T10:19:27.000Z"
      },
      "links": [
        {
          "rel": [
            "self"
          ],
          "href": "http://api.app.me:3000/v1/artists/7"
        }
      ],
      "entities": [
        [
          {
            "class": [
              "albums"
            ],
            "href": "http://api.app.me:3000/v1/albums/id/8,9,10,11/page/1/per/10",
            "rel": [
              "related"
            ]
          },
          {
            "class": [
              "genre"
            ],
            "rel": [
              "related"
            ],
            "properties": {
              "id": 7,
              "title": "Soundtrack",
              "created_at": "2016-01-30T10:19:27.000Z",
              "updated_at": "2016-01-30T10:19:27.000Z"
            },
            "links": [
              {
                "rel": [
                  "collection"
                ],
                "href": "http://api.app.me:3000/v1/genres"
              }
            ]
          }
        ]
      ]
    },
    {
      "class": [
        "artist"
      ],
      "rel": [
        "item"
      ],
      "properties": {
        "id": 8,
        "title": "Harry Gregson-Williams",
        "country": "UK",
        "genre_id": 7,
        "created_at": "2016-01-30T10:19:27.000Z",
        "updated_at": "2016-01-30T10:19:27.000Z"
      },
      "links": [
        {
          "rel": [
            "self"
          ],
          "href": "http://api.app.me:3000/v1/artists/8"
        }
      ],
      "entities": [
        [
          {
            "class": [
              "genre"
            ],
            "rel": [
              "related"
            ],
            "properties": {
              "id": 7,
              "title": "Soundtrack",
              "created_at": "2016-01-30T10:19:27.000Z",
              "updated_at": "2016-01-30T10:19:27.000Z"
            },
            "links": [
              {
                "rel": [
                  "collection"
                ],
                "href": "http://api.app.me:3000/v1/genres"
              }
            ]
          }
        ]
      ]
    },
    {
      "class": [
        "artist"
      ],
      "rel": [
        "item"
      ],
      "properties": {
        "id": 9,
        "title": "Dave Brubeck ",
        "country": "USA",
        "genre_id": 5,
        "created_at": "2016-01-30T10:19:27.000Z",
